[book]
authors = ["Jeremy Avigad", "Leonardo de Moura", "Soonho Kong", "Sebastian Ullrich"]
language = "en"
multilingual = false
src = "."
title = "Theorem Proving in Lean 4"

[build]
build-dir = "out"

[output.html]
git-repository-url = "https://github.com/leanprover/lean4"
additional-css = ["alectryon.css", "pygments.css"]
additional-js = ["alectryon.js"]
mathjax-support = true

[output.html.fold]
enable = true
level = 2

[output.html.playground.boring-prefixes]
lean = "# "
